'use client'

import { useState } from 'react'
import { ArrowDown, ArrowUpRight, Menu, Star, X } from 'lucide-react'
import { site } from '@/lib/data'

function Img({ src, alt, className = '' }: { src: string; alt: string; className?: string }) {
  return <div className={`group relative overflow-hidden ${className}`}><img src={src} alt={alt} className="absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-105" /></div>
}
function Heading({ eyebrow, title, light = false }: { eyebrow: string; title: string; light?: boolean }) {
  return <div className="space-y-4"><p className={`font-mono text-[10px] uppercase tracking-[0.24em] ${light ? 'text-gold' : 'text-berry'}`}>{eyebrow}</p><h2 className={`font-serif text-4xl leading-[1.05] tracking-[-0.03em] sm:text-6xl ${light ? 'text-cream' : 'text-ink'}`}>{title}</h2></div>
}
function Header() {
  const [open, setOpen] = useState(false)
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-cream/20 bg-ink/85 text-cream backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8"><a href="#top" className="font-serif text-xl tracking-tight">{site.brand}</a><nav className="hidden gap-6 md:flex">{site.nav.map(([label, href]) => <a key={href} href={href} className="font-mono text-[10px] uppercase tracking-[0.13em] text-cream/80 transition-colors hover:text-gold">{label}</a>)}</nav><button className="md:hidden" aria-label={open ? 'Chiudi menu' : 'Apri menu'} onClick={() => setOpen(!open)}>{open ? <X size={22} /> : <Menu size={22} />}</button></div>{open && <nav className="flex flex-col gap-5 border-t border-cream/15 bg-ink px-5 py-6 md:hidden">{site.nav.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)} className="font-mono text-xs uppercase tracking-[0.15em]">{label}</a>)}</nav>}</header>
}
function PageImage({ src, alt, className }: { src: string; alt: string; className?: string }) { return <Img src={src} alt={alt} className={`relative ${className ?? ''}`} /> }
export default function OsteriaPage() {
  const [quote, setQuote] = useState(0)
  return <main id="top" className="overflow-hidden bg-paper text-ink">
    <Header />
    <section className="relative flex h-[92svh] min-h-[620px] items-end bg-ink text-cream"><PageImage src={site.hero.image} alt="Lavorazione artigianale della lana" className="absolute inset-0 h-full w-full opacity-75" /><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/35 to-transparent" /><div className="relative mx-auto w-full max-w-7xl px-5 pb-16 pt-40 sm:px-8 sm:pb-24"><p className="mb-5 font-mono text-[10px] uppercase tracking-[0.25em] text-gold">{site.kicker}</p><h1 className="max-w-4xl font-serif text-6xl leading-[0.88] tracking-[-0.05em] sm:text-8xl lg:text-[9.5rem]">{site.hero.title}</h1><div className="mt-8 flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><p className="max-w-md text-base leading-7 text-cream/80 sm:text-lg">{site.hero.text}</p><a href="#beetoneghe" aria-label="Scopri la storia" className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full border border-cream/50 transition-colors hover:bg-cream hover:text-ink"><ArrowDown size={18} /></a></div></div></section>
    <section id="beetoneghe" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 sm:px-8 sm:py-32 lg:grid-cols-[0.8fr_1.2fr] lg:gap-24"><Heading eyebrow={site.intro.eyebrow} title={site.intro.title} /><div className="space-y-8 text-lg leading-8 text-ink/75"><div className="space-y-5">{site.intro.paragraphs.map(p => <p key={p}>{p}</p>)}</div><blockquote className="border-l-2 border-berry pl-5 font-serif text-3xl leading-tight text-berry">{site.intro.quote}</blockquote></div></section>
    <section id="filo" className="mx-auto grid max-w-7xl gap-10 px-5 pb-24 sm:px-8 sm:pb-32 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:gap-24"><PageImage src={site.story.image} alt="Mani che filano la lana" className="aspect-[4/5]" /><div className="space-y-7"><Heading eyebrow={site.story.eyebrow} title={site.story.title} /><p className="max-w-lg text-lg leading-8 text-ink/75">{site.story.text}</p><a href="#creazioni" className="inline-flex items-center gap-3 border-b border-ink pb-2 font-mono text-[10px] uppercase tracking-[0.18em]">Guarda le creazioni <ArrowUpRight size={15} /></a></div></section>
    <section className="bg-cream px-5 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-7xl"><Heading eyebrow="Il gesto" title="Tre gesti, un solo filo." /><div className="mt-14 grid gap-8 md:grid-cols-3">{site.process.map((item, i) => <article key={item.title}><PageImage src={item.image} alt={item.title} className="aspect-[4/5]" /><div className="flex gap-5 pt-5"><span className="font-mono text-xs text-berry">0{i + 1}</span><div><h3 className="font-serif text-2xl">{item.title}</h3><p className="mt-3 text-sm leading-6 text-ink/65">{item.text}</p></div></div></article>)}</div></div></section>
    <section id="colori" className="mx-auto grid max-w-7xl gap-10 px-5 py-24 sm:px-8 sm:py-32 lg:grid-cols-2 lg:items-center lg:gap-24"><div className="order-2 space-y-7 lg:order-1"><Heading eyebrow={site.colors.eyebrow} title={site.colors.title} /><p className="max-w-md text-lg leading-8 text-ink/75">{site.colors.text}</p><div className="flex gap-2 pt-2"><i className="h-10 w-10 rounded-full bg-berry" /><i className="h-10 w-10 rounded-full bg-moss" /><i className="h-10 w-10 rounded-full bg-gold" /></div></div><PageImage src={site.colors.image} alt="Fiori e piante per la tintura naturale" className="order-1 aspect-square lg:order-2" /></section>
    <section id="creazioni" className="bg-paper px-5 pb-24 sm:px-8 sm:pb-32"><div className="mx-auto max-w-7xl"><Heading eyebrow="Fatte qui" title="Le creazioni" /><div className="mt-14 grid grid-cols-2 gap-4 sm:gap-6"><article className="col-span-2"><PageImage src={site.creations[0][1]} alt={site.creations[0][0]} className="aspect-[16/8]" /></article>{site.creations.slice(1).map(([title, image]) => <article key={title}><PageImage src={image} alt={title} className="aspect-square" /></article>)}</div></div></section>
    <section id="osteria" className="bg-dark px-5 py-24 text-cream sm:px-8 sm:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-end"><div><Heading eyebrow={site.osteria.eyebrow} title={site.osteria.title} light /></div><p className="max-w-lg text-lg leading-8 text-cream/70">{site.osteria.text}</p></div><div className="mt-14 grid grid-cols-3 gap-3">{site.osteria.images.map((image, i) => <PageImage key={image} src={image} alt={`L'Osteria, dettaglio ${i + 1}`} className={`aspect-[3/4] ${i === 1 ? 'mt-10' : ''}`} />)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32"><Heading eyebrow="Quello in cui crediamo" title="Il filo che ci tiene insieme." /><div className="mt-14 grid gap-8 border-t border-ink/20 pt-8 md:grid-cols-3">{site.values.map(([num, label]) => <div key={num} className="flex gap-5"><span className="font-mono text-sm text-gold">{num}</span><h3 className="max-w-[12rem] font-serif text-2xl leading-tight">{label}</h3></div>)}</div></section>
    <section className="bg-cream px-5 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-4xl text-center"><p className="font-mono text-[10px] uppercase tracking-[0.24em] text-berry">Parole dal tavolo</p><blockquote className="mt-8 min-h-32 font-serif text-4xl leading-tight tracking-tight text-ink sm:text-6xl">{site.testimonials[quote][0]}</blockquote><p className="mt-6 text-sm text-ink/60">{site.testimonials[quote][1]}</p><div className="mt-10 flex justify-center gap-3"><button aria-label="Recensione precedente" onClick={() => setQuote((quote - 1 + site.testimonials.length) % site.testimonials.length)} className="rounded-full border border-ink/30 p-3 hover:bg-paper"><ArrowUpRight className="rotate-[-135deg]" size={16} /></button><button aria-label="Recensione successiva" onClick={() => setQuote((quote + 1) % site.testimonials.length)} className="rounded-full border border-ink/30 p-3 hover:bg-paper"><ArrowUpRight className="rotate-45" size={16} /></button></div></div></section>
    <section className="bg-berry px-5 py-24 text-cream sm:px-8 sm:py-32"><div className="mx-auto flex max-w-7xl flex-col gap-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.24em] text-gold">{site.cta.eyebrow}</p><h2 className="mt-4 max-w-xl font-serif text-5xl leading-[0.95] tracking-tight sm:text-7xl">{site.cta.title}</h2><p className="mt-6 max-w-md leading-7 text-cream/75">{site.cta.text}</p></div><a href="mailto:ciao@osteriadellalana.it" className="inline-flex items-center gap-3 border-b border-cream pb-2 font-mono text-[10px] uppercase tracking-[0.18em]">Scrivici <ArrowUpRight size={15} /></a></div></section>
    <footer className="bg-dark px-5 py-8 text-cream/60 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-5 text-xs sm:flex-row sm:items-center sm:justify-between"><span className="font-serif text-lg text-cream">{site.brand}</span><span>Valsassina, Lecco · Italia</span><a href="#top" className="flex items-center gap-2 hover:text-cream">Torna su <ArrowUpRight size={14} className="rotate-[-45deg]" /></a><a href="#top" aria-label="Instagram" className="hover:text-cream"><Star size={17} /></a></div></footer>
  </main>
}
